name: Frontend Build and hosting in aws using Cloudfront and S3

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Dist File
    runs-on: self-hosted
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Package.json version increase
        run: |
          git config --global user.name 'bibek65'
          git config --global user.email 'bkarna65@gmail.com'
          npm version patch --no-git-tag-version
          git add package.json
          git commit -m "Increase package.json version and push"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/bibek65/Backend.git

      - name: Push dist to S3 bucket
        run: |
          aws s3 cp ./dist/ s3://bibek-s3-bucket --recursive
      - name: Invalidate Cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DID }} --paths "/*"
