name: Frontend Build and hosting in aws using Cloudfront and S3

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Dist File and Increase package.json and Copy to S3 and invalidate cloudfront
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Push dist to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./dist/ s3://bibek-s3-bucket --recursive
