name: Backend image Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Frontend image
        run: |
          docker build -t frontend .
      - name: Push to S3 bucket
        run: |
          aws s3 cp ./dist/ s3://bibek-s3-bucket --recursive
