name: Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    name: Frontend
    runs-on: self-hosted
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./frontend
          sonarHost: http://192.168.220.140:9000
          sonarToken: ${{ secrets.SONAR_TOKEN }}

      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
