name: Frontend

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    name: Frontend Test
    runs-on: self-hosted
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #   with:
      #     projectBaseDir: ./frontend
      #     args: >
      #       -Dsonar.projectKey=ReactProject

      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and build
        run: |
          docker build -t frontendimg .
          docker run -d --name frontend -p 80:80 frontendimg
        working-directory: ./frontend

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "http://192.168.220.139"
