name: Backend image Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Push dist to S3 bucket
        run: |
          aws s3 cp ./dist/ s3://bibek-s3-bucket --recursive
